# Generated by Django 3.2.8 on 2021-11-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_num', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_model.departments')),
            ],
            options={
                'verbose_name_plural': 'Hosts',
                'unique_together': {('host', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Increments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_name', models.CharField(max_length=200, unique=True)),
                ('total_amount', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Increments',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('increments', models.ManyToManyField(to='DB_model.Increments')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('increments', models.ManyToManyField(to='DB_model.Increments')),
            ],
            options={
                'verbose_name_plural': 'Software',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_model.departments')),
                ('products', models.ManyToManyField(to='DB_model.Products')),
                ('software', models.ManyToManyField(to='DB_model.Software')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'unique_together': {('user_name', 'department')},
            },
        ),
        migrations.AddField(
            model_name='software',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_model.vendors'),
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_model.vendors'),
        ),
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DB_model.hosts')),
                ('increment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DB_model.increments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DB_model.users')),
            ],
            options={
                'verbose_name_plural': 'Main Table',
            },
        ),
        migrations.AddField(
            model_name='increments',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_model.vendors'),
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('state', models.BooleanField()),
                ('description', models.CharField(max_length=500, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_model.vendors')),
            ],
            options={
                'verbose_name_plural': 'Servers',
                'unique_together': {('server_name', 'port')},
            },
        ),
    ]
